export const db = {
    tutorials: [
        { id: 1, title: 'Tuto 1' },
        { id: 2, title: 'Tuto 2' },
        { id: 3, title: 'Tuto 3' },
        { id: 4, title: 'Tuto 4' },
        { id: 5, title: 'Tuto 5' },
        { id: 6, title: 'Tuto 6' },
        { id: 7, title: 'Tuto 7' },
        { id: 8, title: 'Tuto 8' },
        { id: 9, title: 'Tuto 9' },
        { id: 10, title: 'Tuto 10' },
        { id: 11, title: 'Tuto 11' },
        { id: 12, title: 'Tuto 12' },
        { id: 13, title: 'Tuto 13' },
        { id: 14, title: 'Tuto 14' },
        { id: 15, title: 'Tuto 15' },
        { id: 16, title: 'Tuto 16' },
        { id: 17, title: 'Tuto 17' },
        { id: 18, title: 'Tuto 18' },
        { id: 19, title: 'Tuto 19' },
        { id: 20, title: 'Tuto 20' },
        { id: 21, title: 'Tuto 21' },
        { id: 22, title: 'Tuto 22' },
        { id: 23, title: 'Tuto 23' },
        { id: 24, title: 'Tuto 24' },
        { id: 25, title: 'Tuto 25' },
        { id: 26, title: 'Tuto 26' },
        { id: 27, title: 'Tuto 27' },
        { id: 28, title: 'Tuto 28' },
        { id: 29, title: 'Tuto 29' },
        { id: 30, title: 'Tuto 30' },
        { id: 31, title: 'Tuto 31' },
        { id: 32, title: 'Tuto 32' },
        { id: 33, title: 'Tuto 33' },
        { id: 34, title: 'Tuto 34' },
        { id: 35, title: 'Tuto 35' },
        { id: 36, title: 'Tuto 36' },
        { id: 37, title: 'Tuto 37' },
        { id: 38, title: 'Tuto 38' },
        { id: 39, title: 'Tuto 39' },
        { id: 40, title: 'Tuto 40' },
    ]
}